#compusolry field apiversion
apiVersion: apps/v1
#compusolry field of defintion
kind: Deployment
#compusolry field information and LABELS about definition a dictionary
metadata:
  name: myfirstdeployment
#labels a dictionary any key values you wish
  labels: 
    env: test
#compusolry field specifications for defintion
spec:
  template:
#compusolry field specification about the pod for this deployment
    metadata:
      name: mynginx
      labels:
        name: mynginx
        tier: backend
    spec:
      containers:
        -
          name: nginx
          image: nginx
#compusolry field specifications selecting pods considered for replication using LABELS must match pod LABEL  
  selector: 
    matchLabels:
      name: mynginx
      tier: backend
  #number of replicas
  replicas: 3